### ISSUE TITLE
[2020] Missing headers

### ISSUE THREAD

**Issue by JMaio** [specknet/pdiot-data#2]
Hi, I've found some data files that seem to be giving trouble - would their owners be able to fix them? Most of these are just missing headers so it'd be really helpful as you've already contributed the accelerometer data. Cheers!

@azamkhan99
https://github.com/specknet/pdiot-data/blob/df29bdb82e66c242ad61112c6c546b2b80d83e96/2020/s1704037/s123456_Walking%20at%20normal%20speed_Chest_Left_1600702738714.csv#L5
@the-ping 
https://github.com/specknet/pdiot-data/blob/df29bdb82e66c242ad61112c6c546b2b80d83e96/2020/s1770036/s1770036_Running_Chest_Left_1603035399338.csv#L5
@benjikershenbaum 
https://github.com/specknet/pdiot-data/blob/df29bdb82e66c242ad61112c6c546b2b80d83e96/2020/s1709221/s1709221_Lying%20down%20on%20stomach_Front%20pocket%20(trouser)_Right_1601389391844.csv#L5
@chanwoochoigit 
https://github.com/specknet/pdiot-data/blob/df29bdb82e66c242ad61112c6c546b2b80d83e96/2020/s1737472/s1737472_Climbing%20stairs_Front%20pocket%20(trouser)_Left_1601161585316.csv#L1
@stylianosc07 
https://github.com/specknet/pdiot-data/blob/df29bdb82e66c242ad61112c6c546b2b80d83e96/2020/s1711507/s1711507_Climbing%20stairs_1601410351038.csv#L1

**Comment by mynameisteodora** [comment]
Thanks Joao I have let everyone know
